apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-confidence-config
  namespace: deploy-confidence
data:
  APP_NAME: "deploy-confidence-service"
  APP_VERSION: "0.1.0"
  APP_ENV: "production"
  LOG_LEVEL: "INFO"

  API_HOST: "0.0.0.0"
  API_PORT: "8000"

  PROMETHEUS_URL: "http://kps-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"

  CHECK_INTERVAL_SECONDS: "120"
  DEPLOY_THRESHOLD: "70"

  KUBERNETES_IN_CLUSTER: "true"