apiVersion: v1
kind: Secret
metadata:
  name: deploy-confidence-postgres-secret
  namespace: deploy-confidence
type: Opaque
stringData:
  POSTGRES_DB: deploy_confidence
  POSTGRES_USER: deploy_confidence
  POSTGRES_PASSWORD: change_me
