apiVersion: v1
kind: Secret
metadata:
  name: deploy-confidence-secret
  namespace: deploy-confidence
type: Opaque
stringData:
#   DATABASE_URL: "postgresql+psycopg://deploy_confidence:change_me@deploy-confidence-postgres.deploy-confidence.svc.cluster.local:5432/deploy_confidence"
  DATABASE_URL: "postgresql+psycopg://deploy_confidence:change_me@deploy-confidence-postgres:5432/deploy_confidence"
