APP_STATUS_OK = "ok"
APP_STATUS_DEGRADED = "degraded"
APP_STATUS_FAILED = "failed"

SERVICE_NAME = "deploy-confidence-service"

DEFAULT_API_PREFIX = ""

DEPLOY_STATUS_DEPLOY = "DEPLOY"
DEPLOY_STATUS_CAUTION = "CAUTION"
DEPLOY_STATUS_HOLD = "HOLD"

COMPONENT_NODE_HEADROOM = "node_headroom"
COMPONENT_RESTART_PRESSURE = "restart_pressure"
COMPONENT_IMAGE_PULL_HEALTH = "image_pull_health"
COMPONENT_STARTUP_LATENCY = "startup_latency"
COMPONENT_DEPENDENCY_HEALTH = "dependency_health"

DEFAULT_COMPONENT_WEIGHTS = {
    COMPONENT_NODE_HEADROOM: 0.25,
    COMPONENT_RESTART_PRESSURE: 0.20,
    COMPONENT_IMAGE_PULL_HEALTH: 0.25,
    COMPONENT_STARTUP_LATENCY: 0.15,
    COMPONENT_DEPENDENCY_HEALTH: 0.15,
}
